# Generated by Django 2.0.6 on 2018-06-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.TextField(blank=True)),
                ('model_name', models.TextField(blank=True)),
                ('display_size', models.DecimalField(decimal_places=2, max_digits=2)),
                ('cpu', models.TextField(blank=True)),
                ('ram', models.TextField(blank=True)),
                ('gpu', models.TextField(blank=True)),
            ],
        ),
    ]
