# Generated by Django 2.0.6 on 2018-06-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Manufacturer', models.CharField(max_length=60)),
                ('Model_Name', models.CharField(max_length=100)),
                ('Image', models.ImageField(default=None, upload_to='')),
                ('Screen_Size', models.FloatField()),
                ('CPU', models.CharField(max_length=100)),
                ('RAM', models.DecimalField(decimal_places=0, max_digits=3)),
                ('GPU', models.CharField(max_length=100)),
                ('Camera', models.CharField(max_length=40)),
                ('IO', models.TextField(max_length=480)),
                ('Storage', models.CharField(max_length=100)),
                ('OS', models.CharField(max_length=40)),
                ('Battery_Rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('RAM_Type', models.CharField(max_length=30)),
                ('VRAM', models.DecimalField(decimal_places=1, max_digits=3)),
                ('Internet_Connectivity', models.TextField(max_length=140)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Manufacturer', models.CharField(max_length=60)),
                ('Model_Name', models.CharField(max_length=100)),
                ('Image', models.ImageField(default=None, upload_to='')),
                ('Display_Size', models.FloatField()),
                ('CPU', models.CharField(max_length=100)),
                ('RAM', models.DecimalField(decimal_places=0, max_digits=3)),
                ('GPU', models.CharField(max_length=100)),
                ('Front_Camera', models.DecimalField(decimal_places=1, max_digits=3)),
                ('Rear_Camera', models.DecimalField(decimal_places=1, max_digits=3)),
                ('Weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Resolution', models.CharField(max_length=40)),
                ('Battery_Rating', models.DecimalField(decimal_places=0, max_digits=5)),
                ('Colour', models.CharField(max_length=50)),
                ('SKU', models.CharField(max_length=40)),
                ('OS', models.CharField(max_length=40)),
                ('Storage', models.CharField(max_length=40)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
