# Generated by Django 2.0.6 on 2018-06-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_auto_20180615_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiles',
            name='cpu',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mobiles',
            name='gpu',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mobiles',
            name='manufacturer',
            field=models.TextField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='mobiles',
            name='model_name',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mobiles',
            name='ram',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
    ]
