# Generated by Django 2.0.6 on 2018-06-15 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_auto_20180615_1642'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mobiles',
            new_name='Mobile',
        ),
    ]
