# Generated by Django 2.0.6 on 2018-06-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_auto_20180615_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='ram',
            field=models.TextField(blank=True),
        ),
    ]
