# Generated by Django 2.0.6 on 2018-06-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_auto_20180615_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='ram',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
    ]
